export const businessCategories = [
    "Finance",
    "home decor",
    'manufacturer & exporter',
    'food – baking',
    'food & beverages',
    'legal service',
    'emcee and event planner',
    'wholesaler and retailer',
    'embroidery',
    'maufacturing jewellery',
    'medical clinic',
    'beauty & makeup artist',
    'finance & accounts',
    'trainer',
    'clothing',
    'real estate',
    'insurance',
    "Fine Jewellery",
    "Fashion & Apparel",
    "Beauty & Skincare",
    "Health & Wellness",
    "Event Management & Wedding Planning",
    "Travel & Tourism",
    "Real Estate & Property Consultants",
    "Financial Services",
    "Legal Services",
    "Education & Coaching",
    "Interior Design & Architecture",
    "Graphic Design & Branding",
    "Digital Marketing & Social Media Management",
    "Website & App Development",
    "Home Décor & Furnishings",
    "Food & Beverages",
    "Photography & Videography",
    "Printing & Packaging Solutions",
    "Corporate Gifting & Personalized Gifts",
    "Handicrafts & Artisans",
    "Automobile Sales & Services",
    "Logistics & Courier Services",
    "HR & Recruitment Services",
    "IT Services & Software Solutions",
    "Stationery & Office Supplies",
    "PR & Media Consultancy",
    "Fitness Equipment & Sports Gear",
    "Childcare & Parenting Services",
    "NGOs & Social Enterprises",
    "Agriculture & Organic Products",
    "Other",
    "None",
];
