export const businessCategories = [
  "Artist",
  "Graphic Design & Branding",
  "Hand made Products",
  "Home Décor",
  "Clothing",
  "Wholesaler and Retailer",
  "REAL ESTATE",
  "Sports teacher",
  "Beauty & Skincare",
  "Manufacturer & Exporter",
  "Food- Baking",
  "Pest control service",
  "plant studio",
  "fashion academny",
  "Makeup Artist",
  "Digital Marketing & Social Media Management",
  "Optical Store",
  "Food",
  "Education & Coaching",
  "Beauty & Makeup Artist",
  "Food & Beverages",
  "Legal Service",
  "Health & Wellness",
  "Professional",
  "Gifting & Hampers",
  "DIGITAL MARKETING",
  "Event Management & Wedding Planning",
  "Manufacturing",
  "Finance & Accounts",
  "Holistic Coach & Healer",
  "Fashion & Apparel",
  "Medical Clinic",
  "ARTIST",
  "emcee and event planner",
  "Events",
  "FINANCIAL MANAGEMENT",
  "Medical Service",
  "Cakes & Desserts",
  "ALKALINE WATER",
  "Finance",
  "retail medical store",
  "Social Media Management",
  "Home Décor & Furnishings",
  "Handmade Products",
  "Maufacturing Jewellery",
  "Clothing - Boutique",
  "Real Estate",
  "Other",
  "Tours & Travels",
  "Home Decor",
  "Interior Design & Architecture",
  "Wellness Solutions",
  "CUSTOMIZATION CLOTHING",
  "Corporate Gifting & Personalized Gifts",
  "Vastu consultant",
  "Legal services",
  "Aari Design & Workshop",
  "All types Saress",
  "Social Media",
  "Vastu Consultant & Astrologer",
  "Food – Baking",
  "Trainer",
  "Jewellery",
  "Printing & Packaging Solutions",
  "finance service",
  "Professional Service",
  "Mfg. Dairy & Food Products",
  "Handicrafts & Artisans",
  "HandBlock Print",
  "Customization Clothing",
  "acadmey",
  "Retail Outlet",
  "ENTERTAINMENT",
  "Travel & Tourism",
  "Embroidery",
  "Health & Fitness",
  "Cooking",
  "Beauty",
  "Waterproofing & Structural repairs Services",
  "Insurance",
  "Readymade Blouses",
  "PATHOLOGY",
  "Fine Jewellery",
  "handmade artifical jewellery",
  "STOCK MARKET/SHARE MARKET CLASSES COACHING",
];
